export const themes = {
    default: {
        titleColor: "#2f80ed",
        textColor:  "#434d58",
        iconColor:  "#4c71f2",
        border: "#e4e2e2",
        background: "#fffefe",
    },
    transparent: {
        titleColor: "#006AFF",
        iconColor: "#0579C3",
        textColor: "#417E87",
        border: "#e4e2e2",
        background: "ff#ffff00",
      },
    shadow_red: {
        titleColor: "#9A0000",
        textColor: "#444",
        iconColor: "#4F0000",
        border: "#4F0000",
        background: "ff#ffff00",
      },
    shadow_green: {
        titleColor: "#007A00",
        textColor: "#444",
        iconColor: "#003D00",
        border: "#003D00",
        background: "ff#ffff00",
      },
    shadow_blue: {
        titleColor: "#00779A",
        textColor: "#444",
        iconColor: "#004450",
        border: "#004490",
        background: "ff#ffff00",
      },
    dark: {
        titleColor: "#fff",
        iconColor: "#79ff97",
        textColor: "#9f9f9f",
        border: "#e4e2e2",
        background: "#151515",
      },
    radical: {
        titleColor: "#fe428e",
        iconColor: "#f8d847",
        textColor: "#a9fef7",
        border: "#e4e2e2",
        background: "#141321",
      },
    merko: {
        titleColor: "#abd200",
        iconColor: "#b7d364",
        textColor: "#68b587",
        border: "#e4e2e2",
        background: "#0a0f0b",
      },
    gruvbox: {
        titleColor: "#fabd2f",
        iconColor: "#fe8019",
        textColor: "#8ec07c",
        border: "#e4e2e2",
        background: "#282828",
      },
    gruvbox_light: {
        titleColor: "#b57614",
        iconColor: "#af3a03",
        textColor: "#427b58",
        border: "#e4e2e2",
        background: "#fbf1c7",
      },
    tokyonight: {
        titleColor: "#70a5fd",
        iconColor: "#bf91f3",
        textColor: "#38bdae",
        border: "#e4e2e2",
        background: "#1a1b27",
      },
    onedark: {
        titleColor: "#e4bf7a",
        iconColor: "#8eb573",
        textColor: "#df6d74",
        border: "#e4e2e2",
        background: "#282c34",
      },
    cobalt: {
        titleColor: "#e683d9",
        iconColor: "#0480ef",
        textColor: "#75eeb2",
        border: "#e4e2e2",
        background: "#193549",
      },
    synthwave: {
        titleColor: "#e2e9ec",
        iconColor: "#ef8539",
        textColor: "#e5289e",
        border: "#e4e2e2",
        background: "#2b213a",
      },
    high_contrast: {
        titleColor: "#e7f216",
        iconColor: "#00ffff",
        textColor: "#fff",
        border: "#e4e2e2",
        background: "#000",
      },
    dracula: {
        titleColor: "#ff6e96",
        iconColor: "#79dafa",
        textColor: "#f8f8f2",
        border: "#e4e2e2",
        background: "#282a36",
      },
    prussian: {
        titleColor: "#bddfff",
        iconColor: "#38a0ff",
        textColor: "#6e93b5",
        border: "#e4e2e2",
        background: "#172f45",
      },
    monokai: {
        titleColor: "#eb1f6a",
        iconColor: "#e28905",
        textColor: "#f1f1eb",
        border: "#e4e2e2",
        background: "#272822",
      },
    vue: {
        titleColor: "#41b883",
        iconColor: "#41b883",
        textColor: "#273849",
        border: "#e4e2e2",
        background: "#fffefe",
      },
    vue_dark: {
        titleColor: "#41b883",
        iconColor: "#41b883",
        textColor: "#fffefe",
        border: "#e4e2e2",
        background: "#273849",
      },
    shades_of_purple: {
        titleColor: "#fad000",
        iconColor: "#b362ff",
        textColor: "#a599e9",
        border: "#e4e2e2",
        background: "#2d2b55",
      },
    nightowl: {
        titleColor: "#c792ea",
        iconColor: "#ffeb95",
        textColor: "#7fdbca",
        border: "#e4e2e2",
        background: "#011627",
      },
    buefy: {
        titleColor: "#7957d5",
        iconColor: "#ff3860",
        textColor: "#363636",
        border: "#e4e2e2",
        background: "#ffffff",
      },
    blue_green: {
        titleColor: "#2f97c1",
        iconColor: "#f5b700",
        textColor: "#0cf574",
        border: "#e4e2e2",
        background: "#040f0f",
      },
    algolia: {
        titleColor: "#00AEFF",
        iconColor: "#2DDE98",
        textColor: "#FFFFFF",
        border: "#e4e2e2",
        background: "#050F2C",
      },
    great_gatsby: {
        titleColor: "#ffa726",
        iconColor: "#ffb74d",
        textColor: "#ffd95b",
        border: "#e4e2e2",
        background: "#000000",
      },
    darcula: {
        titleColor: "#BA5F17",
        iconColor: "#84628F",
        textColor: "#BEBEBE",
        border: "#e4e2e2",
        background: "#242424",
      },
    bear: {
        titleColor: "#e03c8a",
        iconColor: "#00AEFF",
        textColor: "#bcb28d",
        border: "#e4e2e2",
        background: "#1f2023",
      },
    solarized_dark: {
        titleColor: "#268bd2",
        iconColor: "#b58900",
        textColor: "#859900",
        border: "#e4e2e2",
        background: "#002b36",
      },
    solarized_light: {
        titleColor: "#268bd2",
        iconColor: "#b58900",
        textColor: "#859900",
        border: "#e4e2e2",
        background: "#fdf6e3",
      },
    chartreuse_dark: {
        titleColor: "#7fff00",
        iconColor: "#00AEFF",
        textColor: "#fff",
        border: "#e4e2e2",
        background: "#000",
      },
    nord: {
        titleColor: "#81a1c1",
        textColor: "#d8dee9",
        iconColor: "#88c0d0",
        border: "#e4e2e2",
        background: "#2e3440",
      },
    gotham: {
        titleColor: "#2aa889",
        iconColor: "#599cab",
        textColor: "#99d1ce",
        border: "#e4e2e2",
        background: "#0c1014",
      },
    material_palenight: {
        titleColor: "#c792ea",
        iconColor: "#89ddff",
        textColor: "#a6accd",
        border: "#e4e2e2",
        background: "#292d3e",
      },
    graywhite: {
        titleColor: "#24292e",
        iconColor: "#24292e",
        textColor: "#24292e",
        border: "#e4e2e2",
        background: "#ffffff",
      },
    vision_friendly_dark: {
        titleColor: "#ffb000",
        iconColor: "#785ef0",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#000000",
      },
    ayu_mirage: {
        titleColor: "#f4cd7c",
        iconColor: "#73d0ff",
        textColor: "#c7c8c2",
        border: "#e4e2e2",
        background: "#1f2430",
      },
    midnight_purple: {
        titleColor: "#9745f5",
        iconColor: "#9f4bff",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#000000",
      },
    calm: {
        titleColor: "#e07a5f",
        iconColor: "#edae49",
        textColor: "#ebcfb2",
        border: "#e4e2e2",
        background: "#373f51",
      },
    flag_india: {
        titleColor: "#ff8f1c",
        iconColor: "#250E62",
        textColor: "#509E2F",
        border: "#e4e2e2",
        background: "#ffffff",
      },
    omni: {
        titleColor: "#FF79C6",
        iconColor: "#e7de79",
        textColor: "#E1E1E6",
        border: "#e4e2e2",
        background: "#191622",
      },
    react: {
        titleColor: "#61dafb",
        iconColor: "#61dafb",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#20232a",
      },
    jolly: {
        titleColor: "#ff64da",
        iconColor: "#a960ff",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#291B3E",
      },
    maroongold: {
        titleColor: "#F7EF8A",
        iconColor: "#F7EF8A",
        textColor: "#E0AA3E",
        border: "#e4e2e2",
        background: "#260000",
      },
    yeblu: {
        titleColor: "#ffff00",
        iconColor: "#ffff00",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#002046",
      },
    blueberry: {
        titleColor: "#82aaff",
        iconColor: "#89ddff",
        textColor: "#27e8a7",
        border: "#e4e2e2",
        background: "#242938",
      },
    slateorange: {
        titleColor: "#faa627",
        iconColor: "#faa627",
        textColor: "#ffffff",
        border: "#e4e2e2",
        background: "#36393f",
      },
    kacho_ga: {
        titleColor: "#bf4a3f",
        iconColor: "#a64833",
        textColor: "#d9c8a9",
        border: "#e4e2e2",
        background: "#402b23",
      },
    outrun: {
        titleColor: "#ffcc00",
        iconColor: "#ff1aff",
        textColor: "#8080ff",
        border: "#e4e2e2",
        background: "#141439",
      },
    ocean_dark: {
        titleColor: "#8957B2",
        iconColor: "#FFFFFF",
        textColor: "#92D534",
        border: "#e4e2e2",
        background: "#151A28",
      },
    city_lights: {
        titleColor: "#5D8CB3",
        iconColor: "#4798FF",
        textColor: "#718CA1",
        border: "#e4e2e2",
        background: "#1D252C",
      },
    github_dark: {
        titleColor: "#58A6FF",
        iconColor: "#1F6FEB",
        textColor: "#C3D1D9",
        border: "#e4e2e2",
        background: "#0D1117",
      },
    github_dark_dimmed: {
        titleColor: "#539bf5",
        iconColor: "#539bf5",
        textColor: "#ADBAC7",
        border: "#373E47",
        background: "#24292F",
      },
    discord_old_blurple: {
        titleColor: "#7289DA",
        iconColor: "#7289DA",
        textColor: "#FFFFFF",
        border: "#e4e2e2",
        background: "#2C2F33",
      },
    aura_dark: {
        titleColor: "#ff7372",
        iconColor: "#6cffd0",
        textColor: "#dbdbdb",
        border: "#e4e2e2",
        background: "#252334",
      },
    panda: {
        titleColor: "19#f9d899",
        iconColor: "19#f9d899",
        textColor: "#FF75B5",
        border: "#e4e2e2",
        background: "#31353a",
      },
    noctis_minimus: {
        titleColor: "#d3b692",
        iconColor: "#72b7c0",
        textColor: "#c5cdd3",
        border: "#e4e2e2",
        background: "#1b2932",
      },
    cobalt2: {
        titleColor: "#ffc600",
        iconColor: "#ffffff",
        textColor: "#0088ff",
        border: "#e4e2e2",
        background: "#193549",
      },
    swift: {
        titleColor: "#000000",
        iconColor: "#f05237",
        textColor: "#000000",
        border: "#e4e2e2",
        background: "#f7f7f7",
      },
    aura: {
        titleColor: "#a277ff",
        iconColor: "#ffca85",
        textColor: "#61ffca",
        border: "#e4e2e2",
        background: "#15141b",
      },
    apprentice: {
        titleColor: "#ffffff",
        iconColor: "#ffffaf",
        textColor: "#bcbcbc",
        border: "#e4e2e2",
        background: "#262626",
      },
    moltack: {
        titleColor: "#86092C",
        iconColor: "#86092C",
        textColor: "#574038",
        border: "#e4e2e2",
        background: "#F5E1C0",
      },
    codeSTACKr: {
        titleColor: "#ff652f",
        iconColor: "#FFE400",
        textColor: "#ffffff",
        border: "#0c1a25",
        background: "#09131B",
      },
    rose_pine: {
        titleColor: "#9ccfd8",
        iconColor: "#ebbcba",
        textColor: "#e0def4",
        border: "#e4e2e2",
        background: "#191724",
      },
    catppuccin_latte: {
        titleColor: "#137980",
        iconColor: "#8839ef",
        textColor: "#4c4f69",
        border: "#e4e2e2",
        background: "#eff1f5",
      },
    catppuccin_mocha: {
        titleColor: "#94e2d5",
        iconColor: "#cba6f7",
        textColor: "#cdd6f4",
        border: "#e4e2e2",
        background: "#1e1e2e",
      },
    date_night: {
        titleColor: "#DA7885",
        textColor: "#E1B2A2",
        iconColor: "#BB8470",
        border: "#170F0C",
        background: "#170F0C",
      },
    one_dark_pro: {
        titleColor: "#61AFEF",
        textColor: "#E5C06E",
        iconColor: "#C678DD",
        border: "#3B4048",
        background: "#23272E",
      },
    rose: {
        titleColor: "#8d192b",
        textColor: "#862931",
        iconColor: "#B71F36",
        border: "#e9d8d4",
        background: "#e9d8d4",
      },
    holi: {
        titleColor: "#5FABEE",
        textColor: "#D6E7FF",
        iconColor: "#5FABEE",
        border: "#85A4C0",
        background: "#030314",
      },
    neon: {
        titleColor: "#00EAD3",
        textColor: "#FF449F",
        iconColor: "#00EAD3",
        border: "#ffffff",
        background: "#000000",
      },
    blue_navy: {
        titleColor: "#82AAFF",
        textColor: "#82AAFF",
        iconColor: "#82AAFF",
        border: "#ffffff",
        background: "#000000",
      },
    calm_pink: {
        titleColor: "#e07a5f",
        textColor: "#edae49",
        iconColor: "#ebcfb2",
        border: "#e1bc29",
        background: "#2b2d40",
      },
    // ambient_gradient: {
    //     titleColor: "#ffffff",
    //     textColor: "#ffffff",
    //     iconColor: "#ffffff",
    //     background: "35,4158d0,c850c0,#ffcc70",
    //   },
};

export default themes;